# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# pip3 install mkdocs
# pip3 install mkdocs-material
pool: Digital

variables:
  docdir: /home/azure/vsnips-doc

steps:
- checkout: self
  persistCredentials: true

- script: echo "$(docdir)"
  displayName: 'Run a one-line script'

- script: |
    pwd
    echo "$(System.DefaultWorkingDirectory)"
  displayName: 'pwd and echo dir'

- script: |
    rsync --delete -rv $(System.DefaultWorkingDirectory)/* $(docdir)
  displayName: 'Sync the doc'

- script: |
    mkdocs gh-deploy
  displayName: 'Sync the doc'

- script: cd $(docdir) && mkdocs build
  displayName: 'Generate the doc'
